modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/Nova-Committee/AvaritiaDelight/issues"
license = "MIT"

[[mods]]
modId = "avaritia_delight"
version = "${version}"
displayName = "Avaritia's Delight"
authors = "IAFEnvoy, MHanHanBing"
description = '''
Do you want to eat some avarita food?
'''
logoFile = "logo.png"

[[dependencies.avaritia_delight]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.avaritia_delight]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.avaritia_delight]]
modId = "architectury"
mandatory = true
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.avaritia_delight]]
modId = "avaritia"
mandatory = true
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.avaritia_delight]]
modId = "farmersdelight"
mandatory = true
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"
